export enum InterestTag {
  ALL = "ALL",
  SPORTS = "SPORTS",
  ART = "ART",
  MUSIC = "MUSIC",
  FOOD = "FOOD",
  EDUCATION = "EDUCATION",
  TECHNOLOGY = "TECHNOLOGY",
  TRAVEL = "TRAVEL",
  NATURE = "NATURE",
  ADVENTURE = "ADVENTURE",
  PHOTOGRAPHY = "PHOTOGRAPHY",
}
